name: boem productions
favicon: null
layout_spectrum: 0.51258
typography_spectrum: 0.53892
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020105'
    - '#a39790'
    - '#3d333d'
    - '#b4b6d1'
    - '#6d5f58'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
